### ISSUE TITLE
Missing default values for precondition fields

### ISSUE THREAD

**Issue by diega** [etclabscore/tests-etc#6]
To maintain compatibility with ETH tests, precondition fields should have default values according to the following table 
| Field | ETH default value |
| - | - |
| _nonce_  | `"0x0" \| "0x00"`  |
| _balance_  | `"0x0" \| "0x00"`  |
| _code_ | `"0x"`|
| _storage_ | `{ }`|

**Comment by meowsbits** [comment]
I am unconvinced that this is a desirable encoding (except for the idea that the tests core-geth generates would have the same encoding).

Here are some references around hex encoding issues, generally in the context of RPC. 
One might argue that these encoding rules apply to RPC, but these are tests, not RPC messages. But as far as I understand, these tests are designed (and implemented) to be run via RPC with `retesteth` to some client for filling; so they are, kind of, RPC data. 

- https://github.com/ethereumjs/ethereumjs-util/issues/79
- https://github.com/ethereum/go-ethereum/issues/14477
- https://github.com/ethereum/execution-apis/issues/40
- https://pkg.go.dev/github.com/ethereum/go-ethereum/common/hexutil

The `pre` field defines some precondition for tests. These preconditions are definitions of account states. 
From what I'm seeing, `nonce` and `balance` are both quantities, and thus should NOT have leading zeros. Further, `besu` seems to configure mainnet's genesis allocations with account states omitting zero-value annotations, eg:

```json
  "alloc": {
    "000d836201318ec6899a67540690382780743280": {
      "balance": "0xad78ebc5ac6200000"
    },
    "001762430ea9c3a26e5749afdb70da5f78ddbb8c": {
      "balance": "0xad78ebc5ac6200000"
    },
```
> https://github.com/hyperledger/besu/blob/main/config/src/main/resources/mainnet.json#L52-L54. 

Here's the JSON schema spec at ethereum/tests (note "ConfusedHexType"):
```json
        "PreStateAccount": {
            "additionalproperties": true,
            "properties": {
                "balance": {
                    "$ref": "#/definitions/ConfusedHexType"
                },
                "code": {
                    "$ref": "#/definitions/HexMaybePrefixOrEmpty"
                },
                "nonce": {
                    "$ref": "#/definitions/ConfusedHexType"
                },
                "storage": {
                    "additionalProperties": false,
                    "patternProperties": {
                        "^0x[0-9a-f]+": {
                            "$ref": "#/definitions/HexData",
                            "description": "storage key with 0x. data is HexData"
                        }
                    },
                    "type": "object"
                }
            },
```
> https://github.com/ethereum/tests/blob/9d91961e98e97ba319e089f31388d4685da9b362/JSONSchema/st-schema.json

**Comment by meowsbits** [comment]
So to sum up so far, it seems there are 2 concerns going on here:

1. __Whether to omit empty__ (zero-value) annotations for state accounts.
2. __Whether zero-padding should be used__ for annotations describing quantities (eg. `nonce`, `balance`).

Does that seem right to you too?

PS. https://github.com/etclabscore/tests-etc/pull/4#pullrequestreview-1124333122 is related.

**Comment by diega** [comment]
I personally prefer to be explicit in the definition of the preconditions, even if those are redundant and easily stated by convention (like zero values default), so in this case I would agree with the `ethereum/tests`
About the padding, you are correct, the JSON-RPC spec applies here and it clearly states that `0x00` and `0x0` should be supported for _balance_ and _nonce_ preconditions so nothing to do about that (I'll modify the description of the issue to match this)
